# Generated by Django 4.0.4 on 2022-05-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_profilemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname on Telegram (if you have it)'),
        ),
    ]
