# Generated by Django 4.0.4 on 2022-05-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_profilemodel_telegram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
