# Generated by Django 4.0.4 on 2022-05-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='slug',
            field=models.SlugField(default='def_slug', unique=True),
            preserve_default=False,
        ),
    ]
