# Generated by Django 4.0.4 on 2022-06-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_commentsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsmodel',
            old_name='message',
            new_name='comment',
        ),
    ]
