# Generated by Django 4.0.4 on 2022-06-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_alter_commentsmodel_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsmodel',
            options={'ordering': ['-create_date']},
        ),
    ]
