# Generated by Django 4.0.4 on 2022-07-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_contactmessagesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
