# Generated by Django 4.0.4 on 2022-07-17 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0011_profilemodel_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2, verbose_name='Course day')),
                ('homework', models.FileField(upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>')),
                ('questions', models.TextField(max_length=2000, verbose_name='Ask our teachers anything')),
                ('status', models.CharField(choices=[('ND', 'Not done'), ('S', 'Submitted'), ('A', 'Accepted'), ('D', 'Denied')], default='ND', max_length=4, verbose_name='Day status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
