# Generated by Django 4.0.4 on 2022-07-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_homeworksubmitmodel_score_profilemodel_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmitmodel',
            name='homework',
            field=models.FileField(upload_to='<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
