# Generated by Django 4.0.4 on 2022-07-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_alter_homeworksubmitmodel_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmitmodel',
            name='homework',
            field=models.FileField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000002896D51BF40>/'),
        ),
    ]
