# Generated by Django 4.0.4 on 2022-07-17 22:45

import club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_alter_homeworksubmitmodel_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmitmodel',
            name='homework',
            field=models.FileField(upload_to=club.models.user_directory_path),
        ),
    ]
