# Generated by Django 4.0.4 on 2022-07-18 02:07

import club.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_alter_homeworksubmitmodel_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=club.models.user_directory_path)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.homeworksubmitmodel')),
            ],
        ),
    ]
