# Generated by Django 4.0.4 on 2022-07-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_homeworkfilesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmitmodel',
            name='homework',
        ),
    ]
